name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v4
      id: node-modules
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-
    - run: npm install
    - run: npm run build
      env:
        PUBLIC_URL: 'https://twitch-vod-sync.github.io'
    - run: npm run check
    - run: npm run test
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/
      if: ${{ github.ref == 'refs/heads/master' }}
