name: Publish Github Pages

on:
  push:
    branches: master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v4
      id: node-modules
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-
    - run: npm install
    - run: npm run build
      env:
        PUBLIC_URL: 'https://twitch-vod-sync.github.io'
    - run: npm run check
    # - run: npm run test # Disabled because there's 3 tests and they're bad
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
