name: Run tests
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - run: pip install -r requirements.txt
    - run: python -u tests.py
